"use client";
import {useEffect,useState} from "react";

const LEVELS=["Foundation","Developing","Proficient","Advanced","Expert"];
const HISTORY_KEY="mah-buddy-quiz-history";
const readHistory=()=>{try{const v=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");return Array.isArray(v)?v.filter(x=>typeof x==="string").slice(-80):[]}catch{return[]}};
const saveHistory=(items)=>{try{localStorage.setItem(HISTORY_KEY,JSON.stringify(items.slice(-80)))}catch{}};

export default function QuizPage(){
 const[topic,setTopic]=useState("");const[difficulty,setDifficulty]=useState("Normal");const[count,setCount]=useState("10");const[custom,setCustom]=useState(25);const[started,setStarted]=useState(false);const[q,setQ]=useState(0);const[selected,setSelected]=useState(null);const[score,setScore]=useState(0);const[questions,setQuestions]=useState([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[learningLevel,setLearningLevel]=useState("Developing");const[profile,setProfile]=useState({age:"",educationLevel:"",goal:""});
 const total=Number(count==='Custom'?custom:count);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("mah-buddy-profile")||"{}");if(LEVELS.includes(p.learningLevel))setLearningLevel(p.learningLevel);setProfile({age:String(p.age||""),educationLevel:String(p.educationLevel||""),goal:String(p.goal||"")})}catch{}},[]);
 async function startQuiz(){setLoading(true);setError("");setScore(0);setQ(0);setSelected(null);try{const previousQuestions=readHistory();const response=await fetch("/api/quiz",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:topic||"General study",difficulty,learningLevel,age:profile.age,currentStudies:profile.educationLevel,goal:profile.goal,count:total,previousQuestions})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not create quiz.");if(!Array.isArray(data.questions)||data.questions.length!==total)throw new Error("Mah Buddy did not create the exact number of unique questions requested. Please try again.");setQuestions(data.questions);saveHistory([...previousQuestions,...data.questions.map(x=>x.q)]);setStarted(true)}catch(e){setError(e.message||"Could not create quiz")}finally{setLoading(false)}}
 if(started&&q>=questions.length)return <main className="quiz"><div className="result"><span>QUIZ COMPLETE</span><h1>{score} / {questions.length}</h1><p>{difficulty} difficulty • {learningLevel} learning level</p><a href="/quiz">New quiz</a></div><style jsx>{css}</style></main>;
 if(started){const item=questions[q];return <main className="quiz"><header><a href="/">←</a><strong>Quiz</strong><b>{q+1} / {questions.length}</b></header><div className="meta"><span>{topic||'General study'}</span><em>{difficulty} • {learningLevel}</em></div><div className="progress"><i style={{width:`${((q+1)/questions.length)*100}%`}}/></div><section><span>QUESTION {q+1}</span><h1>{item.q}</h1>{item.a.map((a,n)=><button key={`${q}-${n}`} className={selected===n?'option selected':'option'} onClick={()=>setSelected(n)}><b>{String.fromCharCode(65+n)}</b>{a}</button>)}</section><button className="next" disabled={selected===null} onClick={()=>{const correct=selected===item.c;setScore(s=>s+(correct?1:0));setSelected(null);setQ(x=>x+1)}}>{q+1===questions.length?'Finish':'Next question'} →</button><style jsx>{css}</style></main>}
 return <main className="setup"><a className="back" href="/">← Back</a><div className="hero"><span>QUIZ</span><h1>Test your understanding.</h1><p>Questions change every time and match your difficulty, learning level, age and current studies.</p></div><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Chemistry, maths, history"/></label><label>Difficulty<div className="choices">{['Easy','Normal','Hard'].map(x=><button key={x} className={difficulty===x?'selected':''} onClick={()=>setDifficulty(x)}>{x}</button>)}</div></label><label>Number of questions<div className="choices">{['5','10','20'].map(x=><button key={x} className={count===x?'selected':''} onClick={()=>setCount(x)}>{x}</button>)}<button className={count==='Custom'?'selected':''} onClick={()=>setCount('Custom')}>Custom</button></div>{count==='Custom'&&<input type="number" min="1" max="100" value={custom} onChange={e=>setCustom(Math.max(1,Math.min(100,Number(e.target.value)||1)))}/>}</label><div className="level"><span>Your learning profile</span><b>{learningLevel}</b><small>Age: {profile.age||'not set'} • Current studies: {profile.educationLevel||'not set'} • Goal: {profile.goal||'not set'}</small></div>{error&&<p className="error">{error}</p>}<button className="start" disabled={loading} onClick={startQuiz}>{loading?'Creating unique questions…':'Start quiz →'}</button><style jsx>{css}</style></main>}

const css=`*{box-sizing:border-box}.setup,.quiz{min-height:100svh;background:#f7f7fa;color:#18181b;font-family:Inter,system-ui,sans-serif;padding:22px max(16px,calc((100vw - 680px)/2)) 100px}.back,.quiz header a{color:#555;text-decoration:none;font-size:13px}.hero{margin:24px 0;padding:28px;border-radius:26px;background:linear-gradient(135deg,#eeebff,#fff 65%,#f7eafa);border:1px solid #e3e0e9}.hero span,.meta span,.result span{font-size:9px;letter-spacing:.16em;font-weight:850;color:#6d5dfc}.hero h1{font-size:46px;line-height:.98;letter-spacing:-.06em;margin:9px 0}.hero p{color:#777;margin:0;font-size:13px}.setup label{display:block;font-size:12px;font-weight:800;margin:16px 0}.setup input{display:block;width:100%;margin-top:7px;padding:13px;border:1px solid #dddde5;border-radius:13px;background:#fff;outline:0}.choices{display:flex;gap:7px;margin-top:8px;flex-wrap:wrap}.choices button{border:1px solid #dddde5;background:#fff;border-radius:11px;padding:10px 15px;font-weight:700;color:#666}.choices button.selected{background:#eeeaff;color:#6551dc;border-color:#bdb3ff}.level{margin-top:18px;padding:13px 14px;border:1px solid #e0dfe7;border-radius:14px;background:#fff;display:grid;grid-template-columns:1fr auto;gap:4px 12px}.level span{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#777;font-weight:800}.level b{font-size:12px;color:#6551dc}.level small{grid-column:1/-1;color:#888;font-size:11px}.error{color:#b42318;font-size:12px}.start,.next{width:100%;border:0;border-radius:14px;background:#18181b;color:#fff;padding:14px;font-weight:800;margin-top:18px}.start:disabled{opacity:.45}.next:disabled{opacity:.4}.quiz header{display:flex;align-items:center;gap:14px}.quiz header strong{flex:1}.quiz header b{font-size:11px;color:#777}.meta{display:flex;justify-content:space-between;align-items:center;margin:20px 0 10px}.meta em{font-style:normal;font-size:10px;background:#eeeaff;color:#6551dc;padding:7px 10px;border-radius:9px}.progress{height:6px;background:#e6e5eb;border-radius:99px;overflow:hidden}.progress i{display:block;height:100%;background:#6d5dfc}.quiz section{margin-top:28px}.quiz section>span{font-size:9px;letter-spacing:.16em;color:#8e8998;font-weight:850}.quiz section h1{font-size:30px;line-height:1.2;margin:10px 0 22px}.option{width:100%;display:flex;align-items:center;gap:12px;border:1px solid #dedde5;background:#fff;border-radius:14px;padding:14px;margin:9px 0;text-align:left;font-size:14px}.option b{width:28px;height:28px;border-radius:9px;background:#f1eff5;display:grid;place-items:center}.option.selected{border-color:#a99cff;background:#f2efff}.result{max-width:520px;margin:20vh auto;text-align:center;padding:40px;border:1px solid #e3e0e9;border-radius:28px;background:#fff}.result h1{font-size:64px;margin:12px 0}.result p{color:#777}.result a{display:block;margin-top:20px;padding:13px;border-radius:13px;background:#18181b;color:#fff;text-decoration:none;font-weight:800}`;