import { google } from "@ai-sdk/google";
import { generateText } from "ai";
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

type Attachment = { name?: string; type?: string; data?: string };
type InputMessage = { role: "user" | "assistant"; content: string; attachment?: Attachment };
type Profile = { preferredName?: string; buddyName?: string; age?: string; learningLevel?: string; goal?: string; educationLevel?: string };
const MAX_ATTACHMENT_CHARS = 8_500_000, MAX_TEXT_CHARS = 35_000, MAX_MESSAGE_CHARS = 8_000, MAX_HISTORY_MESSAGES = 8;
function imageData(data: string) { const match = data.match(/^data:([^;]+);base64,(.+)$/s); return match ? { mediaType: match[1], data: match[2] } : null; }
function fileData(data: string, fallbackType: string) { const match = data.match(/^data:([^;]+);base64,(.+)$/s); if (match) return { mediaType: match[1] || fallbackType, data: match[2] }; if (/^[A-Za-z0-9+/\s]+={0,2}$/.test(data) && data.replace(/\s/g, "").length > 32) return { mediaType: fallbackType, data: data.replace(/\s/g, "") }; return null; }
function attachmentError(name: string, type: string) { return `The attached file "${name}" (${type}) could not be transferred safely. Please attach it again or use a supported format.`; }
async function getPlatformSettings() { const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if(!url||!key)return {}; const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); const {data}=await client.from("mah_buddy_platform_settings").select("key,value").eq("is_public",true); return Object.fromEntries((data||[]).map((row:any)=>[row.key,row.value])); }
const MAH_BUDDY_IDENTITY=`IDENTITY — MAH BUDDY\nYou are Mah Buddy, the AI assistant of the Mah Buddy app.\nYou were created and developed by ZED_RO Corp.\nIf asked who created, made, developed, or who the developer of Mah Buddy is, answer exactly: "I was created and developed by ZED_RO Corp."\nIf specifically asked who founded, owns, or is behind ZED_RO Corp, answer exactly: "The founder and owner of ZED_RO Corp is Soludo Abraham Arinze."\nNever identify Google, Gemini, OpenAI, Anthropic, or another AI provider as the creator or developer of Mah Buddy.\nIf asked what AI technology powers Mah Buddy, accurately identify the actual provider/model while making clear Mah Buddy itself is created and developed by ZED_RO Corp.`;
const LEVEL_GUIDE:Record<string,string>={Foundation:"A1–A2: very clear everyday English, short sentences, define unfamiliar terms immediately, one idea at a time, simple examples, and strong step-by-step teaching.",Developing:"B1: clear everyday English, moderate sentence length, brief vocabulary explanations, practical examples, and moderate detail.",Proficient:"B2: fluent natural English, subject terminology with brief clarification, deeper explanations, reasoning, and useful examples.",Advanced:"C1: precise academic/professional English, nuanced vocabulary, structured reasoning, detailed explanations, and fewer simplifications.",Expert:"C2: sophisticated precise English, advanced terminology, full technical depth, rigorous reasoning, and minimal simplification."};
const DIFFICULTY_GUIDE:Record<string,string>={Easy:"Easy: basic recall and understanding, straightforward wording, familiar examples, and no unnecessary tricks.",Normal:"Normal: understanding and application, some reasoning, plausible alternatives, and moderate multi-step thinking.",Hard:"Hard: deeper reasoning, application, analysis, challenging distinctions, and academically meaningful challenge."};
const PROFESSIONAL_STUDY_GUIDE=`PROFESSIONAL ANSWERING AND WRITING STANDARD — MANDATORY\n- Mah Buddy is a professional study buddy across subjects and problem-solving domains.\n- Write polished, professional, natural English with correct grammar, spelling, punctuation and precise vocabulary.\n- For questions with a clear answer, state the direct answer FIRST, then explain why.\n- For calculations, give the final result first, then correct working step by step.\n- For definitions, give the definition first, then explanation and an example.\n- For comparisons, state the key distinction first, then compare systematically.\n- Use Markdown when it improves clarity. Avoid filler, childish wording, excessive slang, and unnecessary emojis.\n- Detail should match the question. Never manufacture certainty or facts.`;
export async function POST(request:Request){try{
 const platform=await getPlatformSettings();
 if(platform.maintenance_mode===true)return NextResponse.json({error:"Mah Buddy is temporarily unavailable while maintenance is in progress."},{status:503});
 if(platform.chat_enabled===false)return NextResponse.json({error:"AI chat is temporarily unavailable."},{status:503});
 const body=await request.json(),messages=Array.isArray(body.messages)?body.messages:[];
 const customInstructions=typeof body.customInstructions==="string"?body.customInstructions.trim():"",memory=typeof body.memory==="string"?body.memory.trim():"",requestedDifficulty=typeof body.difficulty==="string"?body.difficulty.trim():"",profile:Profile=body.profile&&typeof body.profile==="object"?body.profile:{};
 if(!messages.length)return NextResponse.json({error:"No messages provided."},{status:400});
 if(!process.env.GOOGLE_GENERATIVE_AI_API_KEY)return NextResponse.json({error:"Mah Buddy AI is not connected yet. Add GOOGLE_GENERATIVE_AI_API_KEY in Vercel Environment Variables."},{status:503});
 const normalized=messages.filter((message:any)=>message&&(message.role==="user"||message.role==="assistant")&&typeof message.content==="string").slice(-MAX_HISTORY_MESSAGES) as InputMessage[];
 const modelMessages=normalized.map(message=>{const attachment=message.attachment;if(!attachment?.data)return{role:message.role,content:message.content.slice(0,MAX_MESSAGE_CHARS)};const type=attachment.type||"application/octet-stream",name=attachment.name||"attached file",rawData=attachment.data;if(rawData.length>MAX_ATTACHMENT_CHARS)return{role:message.role,content:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\nThe attachment "${name}" is too large to process. Please choose a smaller file.`};if(type.startsWith("image/")){const image=imageData(rawData);if(image)return{role:message.role,content:[{type:"text" as const,text:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\nAttached image: ${name}. Analyze the image as part of the user's request.`},{type:"file" as const,data:image.data,mediaType:image.mediaType}]};return{role:message.role,content:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\n${attachmentError(name,type)}`};}if(type==="application/pdf"||type.startsWith("audio/")||type.startsWith("video/")){const file=fileData(rawData,type);if(file)return{role:message.role,content:[{type:"text" as const,text:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\nAttached file: ${name}. Analyze this file as part of the user's request.`},{type:"file" as const,data:file.data,mediaType:file.mediaType}]};return{role:message.role,content:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\n${attachmentError(name,type)}`};}if(["text/plain","text/markdown","text/csv","application/json","text/html"].includes(type))return{role:message.role,content:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\nAttached file: ${name}\n\nFile contents:\n${rawData.slice(0,MAX_TEXT_CHARS)}`};return{role:message.role,content:`${message.content.slice(0,MAX_MESSAGE_CHARS)}\n\nThe user attached a file named "${name}" (${type}), but this file type is not currently supported for content analysis. Tell the user which supported format to use instead.`};});
 const profileName=typeof profile.preferredName==="string"?profile.preferredName.trim():"",buddyName=typeof profile.buddyName==="string"?profile.buddyName.trim():"Mah Buddy",level=typeof profile.learningLevel==="string"?profile.learningLevel.trim():"",age=typeof profile.age==="string"?profile.age.trim():"",currentStudies=typeof profile.educationLevel==="string"?profile.educationLevel.trim():"";
 const levelGuide=LEVEL_GUIDE[level]||LEVEL_GUIDE.Developing,rawDifficulty=requestedDifficulty==="Medium"?"Normal":requestedDifficulty,difficulty=["Easy","Normal","Hard"].includes(rawDifficulty)?rawDifficulty:(platform.default_difficulty==="Easy"||platform.default_difficulty==="Hard"?platform.default_difficulty:"Normal");
 const profileParts=[profileName?`Preferred user name: ${profileName}`:"",buddyName?`User's chosen name for you: ${buddyName}`:"",age?`User age: ${age}`:"",level?`Standard learning/language level: ${level} — ${levelGuide}`:"",currentStudies?`Current studies: ${currentStudies}`:"",profile.goal?`Learning goal: ${String(profile.goal).slice(0,160)}`:""].filter(Boolean).join("\n");
 const systemParts=[`You are Mah Buddy, a smart, friendly, helpful AI companion and study assistant.\n${MAH_BUDDY_IDENTITY}\nRESPONSE BEHAVIOUR:\n- Adapt every answer to the user's saved learning level.\n- Adapt teaching to the user's age and current studies.\n- Treat learning level, age, and current studies as separate personalization signals.\n- Difficulty is separate from learning level: Easy/Normal/Hard controls challenge.\n- Do not force every response into the same template. Answer naturally and efficiently.\n- Never invent facts.\n\n${PROFESSIONAL_STUDY_GUIDE}\nQUIZ AND PRACTICE RULES:\n- When the user asks for quiz/practice questions, give ONE question at a time and wait for the user's answer.\n- Never provide the question and its answer together unless explicitly asked.\n- After the user answers, mark/explain briefly, then give a NEW question.\n- Every new question must vary its wording, example, concept, or question type. Never repeat a previous question from the conversation.`];
 if(profileParts)systemParts.push(`\nREMEMBERED USER PROFILE:\n${profileParts}`);systemParts.push(`\nACTIVE QUESTION DIFFICULTY: ${difficulty}\n${DIFFICULTY_GUIDE[difficulty]}`);if(customInstructions)systemParts.push(`\nUSER CUSTOM INSTRUCTIONS:\n${customInstructions.slice(0,2000)}`);if(memory)systemParts.push(`\nRECENT CONTEXT:\n${memory.slice(0,2500)}`);
 const requestedLength=Number(platform.max_response_length)||1200,maxOutputTokens=Math.max(200,Math.min(1800,Math.ceil(requestedLength/2)));
 const result=await generateText({model:google(process.env.GEMINI_MODEL||"gemini-3.5-flash-lite"),system:systemParts.join("\n"),messages:modelMessages as any,maxOutputTokens,temperature:.2});
 return NextResponse.json({text:result.text});
}catch(error){console.error("Mah Buddy chat error:",error);const details=error instanceof Error?error.message:"Unknown server error";return NextResponse.json({error:"Mah Buddy could not respond right now.",details:details.slice(0,500)},{status:500});}}
