"use client";
import {useEffect} from "react";
import {supabase} from "../lib/supabase";
type StoredMessage={role:"user"|"assistant"|"system";content:string};
type StoredChat={id:string;title:string;messages:StoredMessage[];updatedAt:number};
const CHAT_KEY="mah-buddy-chats", LEGACY_CHAT_KEY="mah-buddy-chat", PREFS_KEY="mah-buddy-prefs";
export default function PersistenceBridge({userId,onSignOut}:{userId:string;onSignOut?:()=>void}){useEffect(()=>{if(!supabase||!userId)return;const client=supabase;let active=true,timer:ReturnType<typeof setTimeout>|null=null,hydrated=false;
const readChats=():StoredChat[]=>{try{const raw=localStorage.getItem(CHAT_KEY);if(raw)return JSON.parse(raw);const legacy=JSON.parse(localStorage.getItem(LEGACY_CHAT_KEY)||"[]");if(!Array.isArray(legacy)||!legacy.length)return[];const chat:StoredChat={id:crypto.randomUUID(),title:"New chat",messages:legacy.filter((m:any)=>m?.role&&m?.content).map((m:any)=>({role:m.role,content:String(m.content)})),updatedAt:Date.now()};localStorage.setItem(CHAT_KEY,JSON.stringify([chat]));return[chat]}catch{return[]}};
const persist=async()=>{if(!active||!hydrated)return;try{const chats=readChats();const ids=new Set(chats.map(c=>c.id));const{data:remote}=await client.from("conversations").select("id").eq("user_id",userId);const removed=(remote||[]).map(r=>r.id).filter(id=>!ids.has(id));if(removed.length)await client.from("conversations").delete().eq("user_id",userId).in("id",removed);for(const chat of chats){const{error}=await client.from("conversations").upsert({id:chat.id,user_id:userId,title:chat.title||"New chat",updated_at:new Date(chat.updatedAt||Date.now()).toISOString()});if(error)continue;await client.from("messages").delete().eq("conversation_id",chat.id).eq("user_id",userId);if(chat.messages.length)await client.from("messages").insert(chat.messages.map(m=>({conversation_id:chat.id,user_id:userId,role:m.role,content:m.content})));}}catch{}}
const persistPrefs=async()=>{try{const p=JSON.parse(localStorage.getItem(PREFS_KEY)||"{}");const theme=p.theme|| (p.dark?"dark":"system");await client.from("user_settings").upsert({user_id:userId,theme,memory_enabled:p.memory!==false,voice_enabled:p.voice!==false,tts_enabled:p.autoSpeak===true,notifications_enabled:p.notifications!==false,updated_at:new Date().toISOString()})}catch{}};
const schedule=()=>{if(timer)clearTimeout(timer);timer=setTimeout(()=>{void persist();void persistPrefs()},600)};
const hydrate=async()=>{try{const[{data:cs,error},{data:settings}]=await Promise.all([client.from("conversations").select("id,title,updated_at").eq("user_id",userId).order("updated_at",{ascending:false}),client.from("user_settings").select("theme,voice_enabled,tts_enabled,notifications_enabled,memory_enabled").eq("user_id",userId).maybeSingle()]);if(error||!active){hydrated=true;return}if(cs?.length){const{data:ms}=await client.from("messages").select("conversation_id,role,content,created_at").eq("user_id",userId).order("created_at",{ascending:true});const map=new Map<string,StoredMessage[]>();for(const m of ms||[]){const a=map.get(m.conversation_id)||[];a.push({role:m.role,content:m.content});map.set(m.conversation_id,a)}localStorage.setItem(CHAT_KEY,JSON.stringify(cs.map(c=>({id:c.id,title:c.title||"New chat",messages:map.get(c.id)||[],updatedAt:new Date(c.updated_at).getTime()}))))}if(settings)localStorage.setItem(PREFS_KEY,JSON.stringify({theme:settings.theme||"system",voice:settings.voice_enabled!==false,autoSpeak:settings.tts_enabled===true,notifications:settings.notifications_enabled!==false,memory:settings.memory_enabled!==false,instructions:""}));hydrated=true;schedule()}catch{hydrated=true}};
const onStorage=(e:StorageEvent)=>{if(e.key===CHAT_KEY||e.key===LEGACY_CHAT_KEY||e.key===PREFS_KEY)schedule()};window.addEventListener("storage",onStorage);const original=localStorage.setItem.bind(localStorage);localStorage.setItem=(key:string,value:string)=>{original(key,value);if(key===CHAT_KEY||key===LEGACY_CHAT_KEY||key===PREFS_KEY)schedule()};void hydrate();
const signOut=async()=>{try{await client.auth.signOut();onSignOut?.();localStorage.removeItem(CHAT_KEY);localStorage.removeItem(LEGACY_CHAT_KEY);localStorage.removeItem(PREFS_KEY);sessionStorage.removeItem("mah-buddy-hydrated")}catch(e){console.error("Mah Buddy sign out failed",e)}};
const observer=new MutationObserver(()=>{const b=document.querySelector<HTMLButtonElement>(".danger");if(b&&!b.dataset.mahBuddySignout){b.dataset.mahBuddySignout="true";b.addEventListener("click",signOut)}});observer.observe(document.body,{childList:true,subtree:true});
return()=>{active=false;if(timer)clearTimeout(timer);window.removeEventListener("storage",onStorage);localStorage.setItem=original;observer.disconnect()};},[userId,onSignOut]);return null}
